language: csharp
dotnet: 1.0.0-preview2-003131
mono: none

sudo: required

services:
  - docker

before_script:
  - docker-compose up -d postgres-test
  - sleep 3

script:
  - dotnet restore 
  - dotnet test test/TheBooks.Tests/