language: csharp

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003131
      mono: none
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none

services:
  - docker

before_script:
  - docker-compose up -d postgres-test

script:
  - dotnet restore 
  - npm install
  - dotnet test test/TheBooks.Tests/